name = "lomote"
main = "./.output/server/index.mjs"
compatibility_date = "2024-11-01"

# 配置D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "lomote"
database_id = "f7220c3c-2d76-4e29-8d9c-ecf8c25b5fcd"